In [1]:
# Libería de tensor flow
import tensorflow as tf
# Estas dos líneas es para que funcione el placeholder
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior() 

In [2]:
# Definición de una constante
constante = tf.constant([2.0,3,4], dtype=tf.float32,name='Constante1')

In [3]:
# Atributos de la constante
print(constante)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [30]:
# Para que funcione el placeholder hay que cargar las librerías
# del tensorflow de manera distinta
# Placeholder es una variable que se crea de inicio vacia, pero 
# servira para ir rellenandola más adelante. Normalmente se 
# usan para el "input" de data
# En este ejemplo se usa la versión que sustituye a la antigua
#apartado = tf.placeholder(dtype=tf.float32, name='Variable1') # Version v1
apartado = tf.keras.Input(name='Variable1', shape=(), dtype=tf.float32)

In [31]:
# Atributos del placeholder
print(apartado)

Tensor("Variable1_1:0", shape=(None,), dtype=float32)


In [6]:
# Variables
# Es un atributo que pueda cambiar de valor a lo largo del programa.
variable = tf.Variable(3,dtype=tf.float32,name="variable1")

In [7]:
# Atributos de variable
print(variable)

<tf.Variable 'variable1:0' shape=() dtype=float32, numpy=3.0>


In [8]:
# Se genera un matriz con todo ceros que luego se puede manipular
# Se indica que tendrá 3 filas y 4 columnas 
matriz = tf.zeros([3,4],tf.int32,name='matriz')

In [9]:
# Atributo
print(matriz)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [10]:
# Se inicializa las variables de nuestra aplicación
# Esto con TF2.0 ya no es necesario
#inicializar = tf.global_variables_initializer()

In [21]:
# Inicializa la sesión de tensorflow. Con TF2.0 no es necesario
#sess = tf.Session()

In [12]:
# Lo que hace es informar nuestras variables en las sesion de TF
# Este paso no es necesario usarlo en TF2.ProcessLookupError0
#sess.run(tf.global_variables_initializer())

In [18]:
# No hace usar sar sess.run para cualquier cosa en TF20
#print(sess.run(constante))

In [33]:
# Se hace la multiplicacion entre apartado y constante
multiplicacion=apartado*constante


Valor de multiplicacion: Tensor("mul_3:0", shape=(3,), dtype=float32)


In [ ]:
# No habrá resultado porque apartado esta vacio
print("Valor de multiplicacion:", multiplicacion)

In [34]:
# Se rellena los valores de apartado
apartado = [[15,10,5]]

In [37]:
# Se vuelve a repetir la formula
multiplicacion=apartado*constante

In [38]:
# Ahora si que devuelve datos. Cada columna se multipla por la constante 
# que es: 2.0, 3 y 4 * 15, 10 y 5. Queda como resultado 30, 30 y 20
print("Valor de multiplicacion:", multiplicacion)

Valor de multiplicacion: tf.Tensor([[30. 30. 20.]], shape=(1, 3), dtype=float32)


In [40]:
# Ejemplo de multiplicación de matrices necesita la forma (M,N)X(N,M)=M,M
# Primera matriz: 2 filas y 2 columnas
a = tf.keras.Input(shape=(2,2), dtype=tf.float32)
# Segunda matriz: 2 filas y 3 columnas
b = tf.keras.Input(shape=(2,3), dtype=tf.float32)

In [44]:
# Datos de la primera matriz
a = [[1,2],[2,2]]
# Datos de la segunda matriz
b = [[12,21,4],[3,2,4]]

In [47]:
# Multiplicación de ambas matrices: (2,2) * (2,3)
mult = tf.matmul(a,b)

In [49]:
# Resultado
print("Resultado de mult: ", mult)

Resultado de mult:  tf.Tensor(
[[18 25 12]
 [30 46 16]], shape=(2, 3), dtype=int32)


In [50]:
# Ejemplo de producto . entre dos vectores
# Primer vector: 3 columnas
c = tf.keras.Input(shape=(3), dtype=tf.float32)
# Segundo vector: 3 columnas
d = tf.keras.Input(shape=(3), dtype=tf.float32)

In [51]:
# Datos para los vectores
# Primer vector
c = [1,2,3]
# Segundo vector
d = [3,2,1]

In [55]:
# Calculo del producto punto
punto = tf.tensordot(c,d,1)

In [56]:
print("Resultado: ", punto)

Resultado:  tf.Tensor(10, shape=(), dtype=int32)
